### ISSUE TITLE
Solve Longest Possible Route in a Matrix with Hurdles

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/450DSA#1]
Problem Link - https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0
Tag - backtracking, implementation
Platform - Gfg
Difficulty - Medium
To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

 - Appropriate title for PR
 - Making another branch with an appropriate name.
 - Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by suju1811** [comment]
Hello sir !! I want to work on this problem please assign it to me

**Comment by Arpitgupta1014** [comment]
Good work @Siddharth7899
