### ISSUE TITLE
Solve Longest alternating subsequence

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/450DSA#2]
Problem Link - https://practice.geeksforgeeks.org/problems/longest-alternating-subsequence5951/1
Tag - backtracking, implementation
Platform - Gfg
Difficulty - Medium
To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

An appropriate title for PR
Making another file with an appropriate name.
Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by singhAman05** [comment]
Hey @Arpitgupta1014 can i work on this problem

**Comment by adityaomar3** [comment]
Hey! I can solve this issue.
