### ISSUE TITLE
Solve Maximum Length of Pair Chain

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/450DSA#5]
Problem Link - https://practice.geeksforgeeks.org/problems/max-length-chain/1
Tag - dp, implementation
Platform - Gfg
Difficulty - Medium
To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

An appropriate title for PR
Making another file with an appropriate name.
Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by hrs-2703** [comment]
sir i want to work on this issue

**Comment by Arpitgupta1014** [comment]
Good work @Hrs-pandit
